In [153]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import stats
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

In [154]:
data = pd.read_csv('Dataset/rf_df.csv')
data

Unnamed: 0  DC024  DC025  DC205  DC206  DC207  DC208  DC209  DC210  \
0               0   11.0    2.0   16.0    1.0    0.0    1.0    0.0    0.0   
1               1   11.0    2.0   31.0    1.0    0.0    1.0    0.0    0.0   
2               2   11.0    2.0   12.0    1.0    0.0    1.0    1.0    1.0   
3               3   11.0    2.0   12.0    1.0    0.0    0.0    0.0    0.0   
4               4   11.0    2.0   12.0    1.0    0.0    1.0    1.0    0.0   
...           ...    ...    ...    ...    ...    ...    ...    ...    ...   
35968       35968   94.0    1.0   17.0    1.0    0.0    0.0    0.0    0.0   
35969       35969   94.0    1.0   12.0    1.0    0.0    1.0    1.0    0.0   
35970       35970   94.0    1.0   12.0    1.0    0.0    1.0    1.0    0.0   
35971       35971   94.0    1.0   12.0    1.0    0.0    1.0    1.0    0.0   
35972       35972   94.0    1.0   12.0    1.0    0.0    1.0    1.0    0.0   

       DC211  ...  DC237f  DC241  DC242  DC244  DC246  DC252  DC270a  DC109  \
0        0.0  ...     0.0    1.0   0.00    0.0    0.0    2.0     1.0   12.0   
1        1.0  ...     0.0    1.0   0.00    1.0    1.0    1.0     2.0   31.0   
2        1.0  ...     0.0    1.0   0.00    1.0    1.0    0.0     4.0   11.0   
3        1.0  ...     0.0    2.0   0.90    1.0    0.0    1.0     1.0   11.0   
4        0.0  ...     0.0    1.0   0.00    0.0    1.0    0.0     2.0   11.0   
...      ...  ...     ...    ...    ...    ...    ...    ...     ...    ...   
35968    0.0  ...     0.0    3.0   0.44    0.0    0.0    0.0     1.0   21.0   
35969    0.0  ...     0.0    1.0   1.00    0.0    0.0    0.0     2.0   11.0   
35970    1.0  ...     0.0    1.0   1.00    0.0    1.0    1.0     1.0   11.0   
35971    1.0  ...     0.0    1.0   1.00    0.0    0.0    0.0     2.0   11.0   
35972    1.0  ...     0.0    1.0   0.00    0.0    0.0    0.0     3.0   11.0   

       DC142a  DC201  
0        60.0      0  
1        70.0      0  
2        75.0      0  
3        85.0      0  
4        65.0      0  
...       ...    ...  
35968     9.0      0  
35969    12.0      0  
35970    48.0      0  
35971    39.0      0  
35972    40.0      0  

[35973 rows x 40 columns]

In [155]:
data.drop('Unnamed: 0', axis=1, inplace=True)
data

DC024  DC025  DC205  DC206  DC207  DC208  DC209  DC210  DC211  DC212  \
0       11.0    2.0   16.0    1.0    0.0    1.0    0.0    0.0    0.0    0.0   
1       11.0    2.0   31.0    1.0    0.0    1.0    0.0    0.0    1.0    0.0   
2       11.0    2.0   12.0    1.0    0.0    1.0    1.0    1.0    1.0    0.0   
3       11.0    2.0   12.0    1.0    0.0    0.0    0.0    0.0    1.0    0.0   
4       11.0    2.0   12.0    1.0    0.0    1.0    1.0    0.0    0.0    0.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
35968   94.0    1.0   17.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0   
35969   94.0    1.0   12.0    1.0    0.0    1.0    1.0    0.0    0.0    0.0   
35970   94.0    1.0   12.0    1.0    0.0    1.0    1.0    0.0    1.0    0.0   
35971   94.0    1.0   12.0    1.0    0.0    1.0    1.0    0.0    1.0    0.0   
35972   94.0    1.0   12.0    1.0    0.0    1.0    1.0    0.0    1.0    1.0   

       ...  DC237f  DC241  DC242  DC244  DC246  DC252  DC270a  DC109  DC142a  \
0      ...     0.0    1.0   0.00    0.0    0.0    2.0     1.0   12.0    60.0   
1      ...     0.0    1.0   0.00    1.0    1.0    1.0     2.0   31.0    70.0   
2      ...     0.0    1.0   0.00    1.0    1.0    0.0     4.0   11.0    75.0   
3      ...     0.0    2.0   0.90    1.0    0.0    1.0     1.0   11.0    85.0   
4      ...     0.0    1.0   0.00    0.0    1.0    0.0     2.0   11.0    65.0   
...    ...     ...    ...    ...    ...    ...    ...     ...    ...     ...   
35968  ...     0.0    3.0   0.44    0.0    0.0    0.0     1.0   21.0     9.0   
35969  ...     0.0    1.0   1.00    0.0    0.0    0.0     2.0   11.0    12.0   
35970  ...     0.0    1.0   1.00    0.0    1.0    1.0     1.0   11.0    48.0   
35971  ...     0.0    1.0   1.00    0.0    0.0    0.0     2.0   11.0    39.0   
35972  ...     0.0    1.0   0.00    0.0    0.0    0.0     3.0   11.0    40.0   

       DC201  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
35968      0  
35969      0  
35970      0  
35971      0  
35972      0  

[35973 rows x 39 columns]

In [156]:
def univariateAnalysis_(column, df):

    print("\nCentral value of  " + column)
    print('-----------------------------')
    print('Mean: ', df[column].mean())
    print('Median: ', df[column].median())
    print('Max: ', df[column].max())
    print('Min: ', df[column].min())
    print('Standard deviation: ', df[column].std())

    #    print("\nDistribution of " + column)
    #    print('-----------------------------')
    #    plt.figure(figsize=(10, 5))
    #    sns.displot(data[column], kde=True)
    #    plt.show()

    print("\nBoxplot of " + column)
    print('-----------------------------')
    plt.figure(figsize=(10, 5))
    sns.boxplot(df[column])
    plt.show()

    #    print('\nhistogram of ' + column)
    #    print('-----------------------------')
    #    plt.figure(figsize=(10, 5))
    #    sns.histplot(data[column], kde=True)
    #    plt.show()

    print('\nOutliers of ' + column)
    print('-----------------------------')
    q1 = df[column].quantile(q=0.25)
    q3 = df[column].quantile(q=0.75)
    iqr = stats.iqr(df[column])

    print(f'Quartile 1: {q1}\nQuartile 3: {q3}')
    print(f'Interquartile Range (IQR): {iqr}')

    print('\nOutliers detection from interquartile range (IQR) of ' + column)
    print('-----------------------------')
    lower_bound =   q1 - 1.5 * iqr
    upper_bound = q3  + 1.5 * iqr
    print('Lower bound: ', lower_bound)
    print('Upper bound: ', upper_bound)
    print(f'number of outliers in lower: {df[df[column] < lower_bound][column].count()}')
    print(f'number of outliers in upper: {df[df[column] > upper_bound][column].count()}')
    print(f'percentage of outliers in lower: {df[df[column] < lower_bound][column].count()*100/len(data)}%')
    print(f'percentage of outliers in upper: {df[df[column] > upper_bound][column].count()*100/len(data)}%')
    mean = df[column].mean()
    median = df[column].median()
    mode = df[column].mode()[0]

    print(f'Median: {median}\tMean: {mean}\tMode: {mode}')
    plt.hist(df[column],bins=100,color='lightblue')
    plt.axvline(mean,color='green',label='Mean')
    plt.axvline(median,color='blue',label='Median')
    plt.legend()
    plt.show()

    print('\nSkewness of ' + column)
    print('-----------------------------')
    print('Skewness: ', df[column].skew())

In [157]:
#df_num = data.select_dtypes(include=['float64', 'int64'])

#for col in df_num.columns:
#    univariateAnalysis_(col, data)

In [158]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [159]:
X

array([[11.,  2., 16., ...,  1., 12., 60.],
       [11.,  2., 31., ...,  2., 31., 70.],
       [11.,  2., 12., ...,  4., 11., 75.],
       ...,
       [94.,  1., 12., ...,  1., 11., 48.],
       [94.,  1., 12., ...,  2., 11., 39.],
       [94.,  1., 12., ...,  3., 11., 40.]])

In [160]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [161]:
X = MinMaxScaler().fit_transform(X)

In [162]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [163]:
X_train

array([[0.24096386, 0.        , 0.04761905, ..., 0.5       , 0.01176471,
        0.1503006 ],
       [0.26506024, 1.        , 0.        , ..., 0.75      , 0.        ,
        0.11422846],
       [0.74698795, 1.        , 0.05952381, ..., 0.        , 0.11764706,
        0.05410822],
       ...,
       [0.12048193, 0.        , 0.        , ..., 0.75      , 0.        ,
        0.06012024],
       [0.73493976, 0.        , 0.        , ..., 0.25      , 0.        ,
        0.04008016],
       [0.26506024, 1.        , 0.        , ..., 0.        , 0.        ,
        0.09018036]])

In [164]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [165]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [166]:
y_test_pred = rf.predict(X_test)

In [167]:
print(f'Accuracy score of test prediction: {accuracy_score(y_test, y_test_pred)}')

Accuracy score of test prediction: 0.9124351371386212


In [168]:
y_train_pred = rf.predict(X_train)

In [169]:
print(f'Accuracy score of train prediction: {accuracy_score(y_train, y_train_pred)}')

Accuracy score of train prediction: 0.9999602875183671


In [170]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [171]:
y_pred = knn.predict(X_test)

In [172]:
print(f'Accuracy score of prediction: {accuracy_score(y_test,y_pred)}')

Accuracy score of prediction: 0.8949221645663454


In [173]:
y_train_pred = knn.predict(X_train)

In [174]:
print(f'Accuracy score of prediction: {accuracy_score(y_train, y_train_pred)}')

Accuracy score of prediction: 0.9176363130932051


In [175]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [176]:
y_pred = dt.predict(X_test)

In [177]:
print(f'Accuracy score of prediction: {accuracy_score(y_test,y_pred)}')

Accuracy score of prediction: 0.8639733135656041


In [178]:
y_train_pred = dt.predict(X_train)

In [179]:
print(f'Accuracy score of prediction: {accuracy_score(y_train, y_train_pred)}')

Accuracy score of prediction: 1.0
